"""do cascade delete on criterion_id in assessments

Revision ID: 0ef701c22506
Revises: 5bfb37164bbd
Create Date: 2025-11-13 15:20:15.590733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef701c22506'
down_revision: Union[str, Sequence[str], None] = '5bfb37164bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_exercise_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_exercise_id_fkey'), 'answers', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
