"""initial commit

Revision ID: 438a772c7c3c
Revises: 
Create Date: 2025-08-21 15:54:04.132189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438a772c7c3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_table('task',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('dictation', 'copying', 'exposition', 'composition', name='tasktype'), nullable=False),
    sa.Column('files_url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_deadline'), 'task', ['deadline'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_index(op.f('ix_task_type'), 'task', ['type'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('teacher', 'student', name='role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('classroom',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_id'), 'classroom', ['id'], unique=False)
    op.create_table('refferal_refferers',
    sa.Column('refferal_id', sa.UUID(), nullable=False),
    sa.Column('refferer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['refferal_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['refferer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('refferal_id', 'refferer_id')
    )
    op.create_table('teacher_students',
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('users_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.create_table('work',
    sa.Column('status', sa.Enum('executing', 'checking', 'archived', name='workstatus'), nullable=False),
    sa.Column('files_url', sa.String(length=100), nullable=False),
    sa.Column('max_point', sa.Integer(), nullable=True),
    sa.Column('final_point', sa.Integer(), nullable=True),
    sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_finish_date'), 'work', ['finish_date'], unique=False)
    op.create_index(op.f('ix_work_id'), 'work', ['id'], unique=False)
    op.create_index(op.f('ix_work_status'), 'work', ['status'], unique=False)
    op.create_table('classroom_students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'classroom_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_students')
    op.drop_index(op.f('ix_work_status'), table_name='work')
    op.drop_index(op.f('ix_work_id'), table_name='work')
    op.drop_index(op.f('ix_work_finish_date'), table_name='work')
    op.drop_table('work')
    op.drop_table('users_tasks')
    op.drop_table('teacher_students')
    op.drop_table('refferal_refferers')
    op.drop_index(op.f('ix_classroom_id'), table_name='classroom')
    op.drop_table('classroom')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_deadline'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
