"""created comments and files tables

Revision ID: 5cd15c544209
Revises: c53481a2f24d
Create Date: 2025-11-05 14:37:23.537455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd15c544209'
down_revision: Union[str, Sequence[str], None] = 'c53481a2f24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_comments_id'), 'type_comments', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('original_mime', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('answers_files',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['type_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('comments_files',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE')
    )
    op.drop_index(op.f('ix_errors_id'), table_name='errors')
    op.drop_table('errors')
    op.drop_index(op.f('ix_error_types_id'), table_name='error_types')
    op.drop_table('error_types')
    op.drop_column('answers', 'file_url')
    op.drop_constraint(op.f('submissions_task_id_fkey'), 'works', type_='foreignkey')
    op.create_foreign_key(None, 'works', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_task_id_fkey'), 'works', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('answers', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('errors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('error_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('errors_answer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['error_type_id'], ['error_types.id'], name=op.f('errors_error_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('errors_pkey'))
    )
    op.create_index(op.f('ix_errors_id'), 'errors', ['id'], unique=False)
    op.create_table('error_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['works.id'], name=op.f('error_types_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('error_types_pkey'))
    )
    op.create_index(op.f('ix_error_types_id'), 'error_types', ['id'], unique=False)
    op.drop_table('comments_files')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('answers_files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_type_comments_id'), table_name='type_comments')
    op.drop_table('type_comments')
    # ### end Alembic commands ###
