"""removed max score from tasks

Revision ID: 5e47696789c8
Revises: b57aea1e119f
Create Date: 2025-10-27 13:52:17.942798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e47696789c8'
down_revision: Union[str, Sequence[str], None] = 'b57aea1e119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'max_score')
    op.drop_column('tasks', 'max_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
