"""add ExerciseCriterions table

Revision ID: b57aea1e119f
Revises: b3a1553a56b6
Create Date: 2025-10-27 12:40:01.351279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57aea1e119f'
down_revision: Union[str, Sequence[str], None] = 'b3a1553a56b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_criterions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_criterions_id'), 'exercise_criterions', ['id'], unique=False)
    op.alter_column('error_types', 'title', new_column_name='name')
    op.alter_column('exercises', 'title', new_column_name='name')
    op.alter_column('subjects', 'title', new_column_name='name')
    op.alter_column('tasks', 'title', new_column_name='name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('error_types', 'name', new_column_name='title')
    op.alter_column('exercises', 'name', new_column_name='title')
    op.alter_column('subjects', 'name', new_column_name='title')
    op.alter_column('tasks', 'name', new_column_name='title')
    op.drop_index(op.f('ix_exercise_criterions_id'), table_name='exercise_criterions')
    op.drop_table('exercise_criterions')
    # ### end Alembic commands ###
