"""make criterions type list['ACriterions']

Revision ID: c53481a2f24d
Revises: ff5eba86daa3
Create Date: 2025-11-03 12:12:41.962256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c53481a2f24d'
down_revision: Union[str, Sequence[str], None] = 'ff5eba86daa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_criterions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_criterions_id'), 'e_criterions', ['id'], unique=False)
    op.create_table('acriterions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('e_criterion_id', sa.UUID(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['e_criterion_id'], ['e_criterions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acriterions_id'), 'acriterions', ['id'], unique=False)
    op.drop_index(op.f('ix_exercise_criterions_id'), table_name='exercise_criterions')
    op.drop_table('exercise_criterions')
    op.add_column('answers', sa.Column('work_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('answers_submission_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'score_recveied')
    op.drop_column('answers', 'submission_id')
    op.add_column('works', sa.Column('finish_date', sa.DateTime(), nullable=True))
    op.alter_column('works', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('works', 'status',
               existing_type=postgresql.ENUM('draft', 'inProgress', 'awaiting_verification', 'verificated', 'canceled', name='statussubmission'),
               type_=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name='statuswork'),
               existing_nullable=False)
    op.drop_index(op.f('ix_submissions_id'), table_name='works')
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.drop_column('works', 'submission_date')
    op.drop_column('works', 'total_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('submission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.create_index(op.f('ix_submissions_id'), 'works', ['id'], unique=False)
    op.alter_column('works', 'status',
               existing_type=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name='statuswork'),
               type_=postgresql.ENUM('draft', 'inProgress', 'awaiting_verification', 'verificated', 'canceled', name='statussubmission'),
               existing_nullable=False)
    op.alter_column('works', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('works', 'finish_date')
    op.add_column('answers', sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('answers', sa.Column('score_recveied', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_submission_id_fkey'), 'answers', 'works', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'work_id')
    op.create_table('exercise_criterions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercise_criterions_exercise_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exercise_criterions_pkey'))
    )
    op.create_index(op.f('ix_exercise_criterions_id'), 'exercise_criterions', ['id'], unique=False)
    op.drop_index(op.f('ix_acriterions_id'), table_name='acriterions')
    op.drop_table('acriterions')
    op.drop_index(op.f('ix_e_criterions_id'), table_name='e_criterions')
    op.drop_table('e_criterions')
    # ### end Alembic commands ###
