"""rename ECriterions and Acriterions

Revision ID: cbfa1f3909a4
Revises: 5cd15c544209
Create Date: 2025-11-11 16:39:50.055585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbfa1f3909a4'
down_revision: Union[str, Sequence[str], None] = '5cd15c544209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_files',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], )
    )
    op.create_table('exercises_files',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE')
    )
    op.rename_table('acriterions', 'assessments')
    op.execute("ALTER INDEX IF EXISTS ix_acriterions_id RENAME TO ix_assessment_id;")
    op.add_column('assessments', sa.Column('points', sa.Integer(), nullable=False))
    op.drop_column("assessments", "completed")

    op.add_column('answers', sa.Column('general_comment', sa.String(), nullable=False))
    op.alter_column('files', 'original_mime',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('files', 'bucket')
    op.add_column('works', sa.Column('сonclusion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'сonclusion')
    op.add_column('files', sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_column('answers', 'general_comment')

    op.rename_table('assessments', 'acriterions' )
    op.execute("ALTER INDEX IF EXISTS ix_assessment_id RENAME TO ix_acriterions_id;")
    op.add_column('acriterions', sa.Column('completed', sa.BOOLEAN(), nullable=False))
    op.drop_column('acriterions','points')

    op.drop_table('exercises_files')
    op.drop_table('tasks_files')
    # ### end Alembic commands ###
