"""do cascade delete on entity_id in entity_files tables

Revision ID: f4fb611a5507
Revises: 0ef701c22506
Create Date: 2025-11-13 15:23:37.975344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fb611a5507'
down_revision: Union[str, Sequence[str], None] = '0ef701c22506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_files_answer_id_fkey'), 'answers_files', type_='foreignkey')
    op.create_foreign_key(None, 'answers_files', 'answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_files_comment_id_fkey'), 'comments_files', type_='foreignkey')
    op.create_foreign_key(None, 'comments_files', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exercises_files_exercise_id_fkey'), 'exercises_files', type_='foreignkey')
    op.create_foreign_key(None, 'exercises_files', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_files_task_id_fkey'), 'tasks_files', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_files', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_files', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_files_task_id_fkey'), 'tasks_files', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'exercises_files', type_='foreignkey')
    op.create_foreign_key(op.f('exercises_files_exercise_id_fkey'), 'exercises_files', 'exercises', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'comments_files', type_='foreignkey')
    op.create_foreign_key(op.f('comments_files_comment_id_fkey'), 'comments_files', 'comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'answers_files', type_='foreignkey')
    op.create_foreign_key(op.f('answers_files_answer_id_fkey'), 'answers_files', 'answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###
