"""rename Submission table to Works table

Revision ID: ff5eba86daa3
Revises: 6a7cfd731a8e
Create Date: 2025-10-31 15:24:07.472215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff5eba86daa3'
down_revision: Union[str, Sequence[str], None] = '6a7cfd731a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
"""rename Submission table to Works table

Revision ID: ff5eba86daa3
Revises: 6a7cfd731a8e
Create Date: 2025-10-31 15:24:07.472215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff5eba86daa3'
down_revision: Union[str, Sequence[str], None] = '6a7cfd731a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OLD_TYPE_NAME = 'statussubmission'
NEW_TYPE_NAME = 'statuswork'
TABLE_NAME = 'works'
COLUMN_NAME = 'status'

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("submissions", "works")
       # ### end Alembic commands ###
    op.execute(
        f"ALTER TYPE {OLD_TYPE_NAME} RENAME TO {NEW_TYPE_NAME};"
    )

    op.alter_column(
        TABLE_NAME, 
        COLUMN_NAME, 
        type_=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name=NEW_TYPE_NAME),
        # server_default=sa.text("'draft'"), # При необходимости
        existing_type=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name=OLD_TYPE_NAME),
        postgresql_using=f"{COLUMN_NAME}::text::statuswork" # Безопасное приведение типов (опционально)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("works", "submissions")

    # 1. Переименование типа ENUM обратно
    op.execute(
        f"ALTER TYPE {NEW_TYPE_NAME} RENAME TO {OLD_TYPE_NAME};"
    )

    # 2. Изменение типа колонки обратно на старый ENUM-тип
    op.alter_column(
        TABLE_NAME, 
        COLUMN_NAME, 
        type_=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name=OLD_TYPE_NAME),
        existing_type=sa.Enum('draft', 'inProgress', 'verification', 'verificated', 'canceled', name=NEW_TYPE_NAME),
        postgresql_using=f"{COLUMN_NAME}::text::{OLD_TYPE_NAME}"
    )
    # ### end Alembic commands ###
